version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"   # Access MySQL at localhost:3307
    networks:
      - app-network

  app:
    build: .
    container_name: user-application
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8080"   # Access app at localhost:8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
